import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GoogleAnalytics from './components/GoogleAnalytics'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BTEB Results Hub - Individual Results, CGPA Calculator, Booklists',
  description: 'BTEB Results Hub: Check individual diploma results instantly and calculate CGPA using BTEB regulations (2010/2016/2022).',
  keywords: [
    'bteb results',
    'bteb result',
    'bteb result diploma',
    'betb result.com',
    'diploma result',
    'diploma result bd',
    'bteb result 2025',
    'diploma result check',
    'bteb result check',
    'diploma in engineering result check',
    'bteb results',
    'diploma results check online',
    'diploma in agriculture result',
    'diploma in engineering result 2025',
    'diploma in agriculture result 2025',
    'nabteb result checker',
    'bteb diploma result',
    'bted result',
    'diploma agriculture result 2025',
    'betb result',
    'bteb result marksheet',
    'bteb result zone 2025',
    'bteb result 2022',
    'bd technical education board result',
    'www.bteb.gov.bd result',
    'technical education board result',
    'diploma results 2025',
    'polytechnic result',
    'polytechnic results 2025',
    'bangladesh technical education board',
    'diploma engineering result',
    'diploma technology result',
    'bteb roll number result',
    'bteb gpa result',
    'diploma semester result',
    'bteb referred subjects',
    'technical education result bangladesh',
    'polytechnic institute result',
    'diploma in technology result',
    'bteb result search',
    'bteb result online',
    'bteb result check online',
    'polytechnic result check',
    'diploma 2025 result',
    'polytechnic 2025 result',
    'bteb exam result',
    'diploma exam result',
    'polytechnic exam result',
    'bteb semester result',
    'diploma semester result',
    'polytechnic semester result',
    'bteb gpa check',
    'diploma gpa check',
    'polytechnic gpa check',
    'bteb institute result',
    'diploma institute result',
    'polytechnic institute result',
    'bteb regulation result',
    'diploma regulation result',
    'polytechnic regulation result',
    'bteb result by roll',
    'diploma result by roll',
    'polytechnic result by roll',
    'bteb result by roll number',
    'diploma result by roll number',
    'polytechnic result by roll number',
    // Bangla keywords
    'বিটিইবি রেজাল্ট',
    'বিটিইবি রেজাল্ট ২০২৫',
    'ডিপ্লোমা রেজাল্ট',
    'ডিপ্লোমা রেজাল্ট ২০২৫',
    'পলিটেকনিক রেজাল্ট',
    'বিটিইবি ডিপ্লোমা রেজাল্ট',
    'বিটিইবি রেজাল্ট চেক',
    'ডিপ্লোমা রেজাল্ট চেক',
    'ইঞ্জিনিয়ারিং রেজাল্ট',
    'কৃষি রেজাল্ট',
    'প্রযুক্তি রেজাল্ট',
    'বিটিইবি রোল নম্বর রেজাল্ট',
    'বিটিইবি জিপিএ রেজাল্ট',
    'সেমিস্টার রেজাল্ট',
    'বাংলাদেশ কারিগরি শিক্ষা বোর্ড রেজাল্ট',
    'বিটিইবি রেজাল্ট অনলাইন',
    'ডিপ্লোমা রেজাল্ট অনলাইন',
    'পলিটেকনিক রেজাল্ট অনলাইন',
    'বিটিইবি রেজাল্ট সার্চ',
    'বিটিইবি রেজাল্ট জোন',
    'বিটিইবি রেজাল্ট মার্কশিট',
    'বিটিইবি রেজাল্ট ২০২২',
    'বিটিইবি রেজাল্ট ২০১৬',
    'বিটিইবি রেজাল্ট ২০১০',
    'কারিগরি শিক্ষা বোর্ড রেজাল্ট',
    'বিটিইবি গভর্নমেন্ট রেজাল্ট',
    'বিটিইবি অফিসিয়াল রেজাল্ট',
    'বিটিইবি রেজাল্ট হাব',
    'বিটিইবি রেজাল্ট চেকার',
    'বিটিইবি রেজাল্ট ভেরিফাই',
    'বিটিইবি রেজাল্ট ডাউনলোড',
    'বিটিইবি রেজাল্ট প্রিন্ট',
    'বিটিইবি রেজাল্ট স্ট্যাটাস',
    'বিটিইবি রেজাল্ট আপডেট',
    'বিটিইবি রেজাল্ট নিউজ',
    'বিটিইবি রেজাল্ট নোটিফিকেশন',
    'বিটিইবি রেজাল্ট রিলিজ',
    'বিটিইবি রেজাল্ট পাবলিশ',
    'বিটিইবি রেজাল্ট ডেট',
    'বিটিইবি রেজাল্ট টাইম',
    'বিটিইবি রেজাল্ট সাইট',
    'বিটিইবি রেজাল্ট ওয়েবসাইট',
    'বিটিইবি রেজাল্ট পোর্টাল',
    'বিটিইবি রেজাল্ট সিস্টেম',
    'বিটিইবি রেজাল্ট সার্ভিস',
    'বিটিইবি রেজাল্ট প্ল্যাটফর্ম',
    'বিটিইবি রেজাল্ট অ্যাপ',
    'বিটিইবি রেজাল্ট মোবাইল',
    'বিটিইবি রেজাল্ট স্মার্টফোন',
    'বিটিইবি রেজাল্ট ট্যাবলেট',
    'বিটিইবি রেজাল্ট কম্পিউটার',
    'বিটিইবি রেজাল্ট ল্যাপটপ',
    'বিটিইবি রেজাল্ট ডেস্কটপ',
    'বিটিইবি রেজাল্ট ব্রাউজার',
    'বিটিইবি রেজাল্ট ইন্টারনেট',
    'বিটিইবি রেজাল্ট ওয়াইফাই',
    'বিটিইবি রেজাল্ট মোবাইল ডেটা',
    'বিটিইবি রেজাল্ট ৪জি',
    'বিটিইবি রেজাল্ট ৫জি',
    'বিটিইবি রেজাল্ট স্পিড',
    'বিটিইবি রেজাল্ট ফাস্ট',
    'বিটিইবি রেজাল্ট কুইক',
    'বিটিইবি রেজাল্ট ইন্সট্যান্ট',
    'বিটিইবি রেজাল্ট রিয়েল টাইম',
    'বিটিইবি রেজাল্ট লাইভ',
    'বিটিইবি রেজাল্ট ডাইরেক্ট',
    'বিটিইবি রেজাল্ট ইমিডিয়েট',
    'বিটিইবি রেজাল্ট প্রম্পট',
    'বিটিইবি রেজাল্ট র্যাপিড',
    'বিটিইবি রেজাল্ট সোয়িফট',
    'বিটিইবি রেজাল্ট এক্সপ্রেস',
    'বিটিইবি রেজাল্ট টার্বো',
    'বিটিইবি রেজাল্ট সুপার ফাস্ট',
    'বিটিইবি রেজাল্ট আল্ট্রা ফাস্ট',
    'বিটিইবি রেজাল্ট হাই স্পিড',
    'বিটিইবি রেজাল্ট ম্যাক্স স্পিড',
    'বিটিইবি রেজাল্ট টপ স্পিড',
    'বিটিইবি রেজাল্ট বেস্ট স্পিড',
    'বিটিইবি রেজাল্ট ফাস্টেস্ট',
    'বিটিইবি রেজাল্ট কুইকেস্ট',
    // Additional BTEB related keywords
    'bteb diploma engineering',
    'bteb diploma technology',
    'bteb diploma agriculture',
    'bteb polytechnic institute',
    'bteb technical education',
    'bteb examination board',
    'bteb result portal',
    'bteb result website',
    'bteb result platform',
    'bteb result system',
    'bteb result database',
    'bteb result archive',
    'bteb result history',
    'bteb result records',
    'bteb result verification',
    'bteb result validation',
    'bteb result authentication',
    'bteb result confirmation',
    'bteb result status',
    'bteb result information',
    'bteb result details',
    'bteb result summary',
    'bteb result overview',
    'bteb result analysis',
    'bteb result statistics',
    'bteb result data',
    'bteb result metrics',
    'bteb result performance',
    'bteb result progress',
    'bteb result achievement',
    'bteb result accomplishment',
    'bteb result success',
    'bteb result completion',
    'bteb result graduation',
    'bteb result certification',
    'bteb result qualification',
    'bteb result credential',
    'bteb result degree',
    'bteb result diploma',
    'bteb result certificate',
    'bteb result transcript',
    'bteb result mark sheet',
    'bteb result grade sheet',
    'bteb result score card',
    'bteb result report card',
    'bteb result academic record',
    'bteb result educational record',
    'bteb result student record',
    'bteb result institutional record',
    'bteb result official record',
    'bteb result formal record',
    'bteb result legal record',
    'bteb result authorized record',
    'bteb result certified record',
    'bteb result verified record',
    'bteb result validated record',
    'bteb result confirmed record',
    'bteb result authenticated record',
    'bteb result genuine record',
    'bteb result original record',
    'bteb result primary record',
    'bteb result source record',
    'bteb result master record',
    'bteb result main record',
    'bteb result central record',
    'bteb result core record',
    'bteb result base record',
    'bteb result fundamental record',
    'bteb result essential record',
    'bteb result key record',
    'bteb result important record',
    'bteb result significant record',
    'bteb result critical record',
    'bteb result vital record',
    'bteb result crucial record',
    'bteb result necessary record',
    'bteb result required record',
    'bteb result mandatory record',
    'bteb result compulsory record',
    'bteb result obligatory record',
    'bteb result binding record',
    'bteb result official document',
    'bteb result formal document',
    'bteb result legal document',
    'bteb result authorized document',
    'bteb result certified document',
    'bteb result verified document',
    'bteb result validated document',
    'bteb result confirmed document',
    'bteb result authenticated document',
    'bteb result genuine document',
    'bteb result original document',
    'bteb result primary document',
    'bteb result source document',
    'bteb result master document',
    'bteb result main document',
    'bteb result central document',
    'bteb result core document',
    'bteb result base document',
    'bteb result fundamental document',
    'bteb result essential document',
    'bteb result key document',
    'bteb result important document',
    'bteb result significant document',
    'bteb result critical document',
    'bteb result vital document',
    'bteb result crucial document',
    'bteb result necessary document',
    'bteb result required document',
    'bteb result mandatory document',
    'bteb result compulsory document',
    'bteb result obligatory document',
    'bteb result binding document',
    // Bangla additional keywords
    'বিটিইবি ডিপ্লোমা ইঞ্জিনিয়ারিং',
    'বিটিইবি ডিপ্লোমা টেকনোলজি',
    'বিটিইবি ডিপ্লোমা এগ্রিকালচার',
    'বিটিইবি পলিটেকনিক ইনস্টিটিউট',
    'বিটিইবি কারিগরি শিক্ষা',
    'বিটিইবি পরীক্ষা বোর্ড',
    'বিটিইবি রেজাল্ট পোর্টাল',
    'বিটিইবি রেজাল্ট ওয়েবসাইট',
    'বিটিইবি রেজাল্ট প্ল্যাটফর্ম',
    'বিটিইবি রেজাল্ট সিস্টেম',
    'বিটিইবি রেজাল্ট ডেটাবেস',
    'বিটিইবি রেজাল্ট আর্কাইভ',
    'বিটিইবি রেজাল্ট হিস্ট্রি',
    'বিটিইবি রেজাল্ট রেকর্ড',
    'বিটিইবি রেজাল্ট ভেরিফিকেশন',
    'বিটিইবি রেজাল্ট ভ্যালিডেশন',
    'বিটিইবি রেজাল্ট অথেন্টিকেশন',
    'বিটিইবি রেজাল্ট কনফার্মেশন',
    'বিটিইবি রেজাল্ট স্ট্যাটাস',
    'বিটিইবি রেজাল্ট ইনফরমেশন',
    'বিটিইবি রেজাল্ট ডিটেইলস',
    'বিটিইবি রেজাল্ট সামারি',
    'বিটিইবি রেজাল্ট ওভারভিউ',
    'বিটিইবি রেজাল্ট অ্যানালাইসিস',
    'বিটিইবি রেজাল্ট স্ট্যাটিস্টিক্স',
    'বিটিইবি রেজাল্ট ডেটা',
    'বিটিইবি রেজাল্ট মেট্রিক্স',
    'বিটিইবি রেজাল্ট পারফরম্যান্স',
    'বিটিইবি রেজাল্ট প্রগ্রেস',
    'বিটিইবি রেজাল্ট অ্যাচিভমেন্ট',
    'বিটিইবি রেজাল্ট অ্যাকমপ্লিশমেন্ট',
    'বিটিইবি রেজাল্ট সাকসেস',
    'বিটিইবি রেজাল্ট কমপ্লিশন',
    'বিটিইবি রেজাল্ট গ্র্যাজুয়েশন',
    'বিটিইবি রেজাল্ট সার্টিফিকেশন',
    'বিটিইবি রেজাল্ট কোয়ালিফিকেশন',
    'বিটিইবি রেজাল্ট ক্রেডেনশিয়াল',
    'বিটিইবি রেজাল্ট ডিগ্রি',
    'বিটিইবি রেজাল্ট ডিপ্লোমা',
    'বিটিইবি রেজাল্ট সার্টিফিকেট',
    'বিটিইবি রেজাল্ট ট্রান্সক্রিপ্ট',
    'বিটিইবি রেজাল্ট মার্ক শিট',
    'বিটিইবি রেজাল্ট গ্রেড শিট',
    'বিটিইবি রেজাল্ট স্কোর কার্ড',
    'বিটিইবি রেজাল্ট রিপোর্ট কার্ড',
    'বিটিইবি রেজাল্ট একাডেমিক রেকর্ড',
    'বিটিইবি রেজাল্ট এডুকেশনাল রেকর্ড',
    'বিটিইবি রেজাল্ট স্টুডেন্ট রেকর্ড',
    'বিটিইবি রেজাল্ট ইনস্টিটিউশনাল রেকর্ড',
    'বিটিইবি রেজাল্ট অফিসিয়াল রেকর্ড',
    'বিটিইবি রেজাল্ট ফরমাল রেকর্ড',
    'বিটিইবি রেজাল্ট লিগাল রেকর্ড',
    'বিটিইবি রেজাল্ট অথরাইজড রেকর্ড',
    'বিটিইবি রেজাল্ট সার্টিফায়েড রেকর্ড',
    'বিটিইবি রেজাল্ট ভেরিফায়েড রেকর্ড',
    'বিটিইবি রেজাল্ট ভ্যালিডেটেড রেকর্ড',
    'বিটিইবি রেজাল্ট কনফার্মড রেকর্ড',
    'বিটিইবি রেজাল্ট অথেন্টিকেটেড রেকর্ড',
    'বিটিইবি রেজাল্ট জেনুইন রেকর্ড',
    'বিটিইবি রেজাল্ট অরিজিনাল রেকর্ড',
    'বিটিইবি রেজাল্ট প্রাইমারি রেকর্ড',
    'বিটিইবি রেজাল্ট সোর্স রেকর্ড',
    'বিটিইবি রেজাল্ট মাস্টার রেকর্ড',
    'বিটিইবি রেজাল্ট মেইন রেকর্ড',
    'বিটিইবি রেজাল্ট সেন্ট্রাল রেকর্ড',
    'বিটিইবি রেজাল্ট কোর রেকর্ড',
    'বিটিইবি রেজাল্ট বেস রেকর্ড',
    'বিটিইবি রেজাল্ট ফান্ডামেন্টাল রেকর্ড',
    'বিটিইবি রেজাল্ট এসেনশিয়াল রেকর্ড',
    'বিটিইবি রেজাল্ট কি রেকর্ড',
    'বিটিইবি রেজাল্ট ইমপর্ট্যান্ট রেকর্ড',
    'বিটিইবি রেজাল্ট সিগনিফিক্যান্ট রেকর্ড',
    'বিটিইবি রেজাল্ট ক্রিটিক্যাল রেকর্ড',
    'বিটিইবি রেজাল্ট ভাইটাল রেকর্ড',
    'বিটিইবি রেজাল্ট ক্রুসিয়াল রেকর্ড',
    'বিটিইবি রেজাল্ট নেসেসারি রেকর্ড',
    'বিটিইবি রেজাল্ট রিকোয়ার্ড রেকর্ড',
    'বিটিইবি রেজাল্ট ম্যান্ডেটরি রেকর্ড',
    'বিটিইবি রেজাল্ট কমপালসরি রেকর্ড',
    'বিটিইবি রেজাল্ট অবলিগেটরি রেকর্ড',
    'বিটিইবি রেজাল্ট বাইন্ডিং রেকর্ড',
    'বিটিইবি রেজাল্ট অফিসিয়াল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ফরমাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট লিগাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট অথরাইজড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট সার্টিফায়েড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ভেরিফায়েড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ভ্যালিডেটেড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট কনফার্মড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট অথেন্টিকেটেড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট জেনুইন ডকুমেন্ট',
    'বিটিইবি রেজাল্ট অরিজিনাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট প্রাইমারি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট সোর্স ডকুমেন্ট',
    'বিটিইবি রেজাল্ট মাস্টার ডকুমেন্ট',
    'বিটিইবি রেজাল্ট মেইন ডকুমেন্ট',
    'বিটিইবি রেজাল্ট সেন্ট্রাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট কোর ডকুমেন্ট',
    'বিটিইবি রেজাল্ট বেস ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ফান্ডামেন্টাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট এসেনশিয়াল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট কি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ইমপর্ট্যান্ট ডকুমেন্ট',
    'বিটিইবি রেজাল্ট সিগনিফিক্যান্ট ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ক্রিটিক্যাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ভাইটাল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ক্রুসিয়াল ডকুমেন্ট',
    'বিটিইবি রেজাল্ট নেসেসারি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট রিকোয়ার্ড ডকুমেন্ট',
    'বিটিইবি রেজাল্ট ম্যান্ডেটরি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট কমপালসরি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট অবলিগেটরি ডকুমেন্ট',
    'বিটিইবি রেজাল্ট বাইন্ডিং ডকুমেন্ট'
    ,
    // User-requested additional tags
    'bteb result hub',
    'bteb board result',
    'bangladesh technical education board result check',
    'bteb.result',
    'btet result 2025',
    'bteb results 2025',
    'btet result',
    'bteb result marksheet download',
    'bteb result 2024',
    // Additional BTEB result tags
    'bteb result',
    'bteb result hub',
    'bteb result diploma',
    'diploma result',
    'betb result.com',
    'bteb result 2025',
    'bteb result marksheet',
    'diploma result bd',
    'diploma result check',
    'bteb results',
    'bteb result check',
    'bteb results hub',
    'bangladesh technical education board result 2025',
    'diploma in engineering result check',
    'diploma in engineering result 2025',
    'diploma in agriculture result 2025',
    'btet result 2025',
    'bteb result portal',
    'diploma results check online',
    'bteb results 2025',
    'diploma in agriculture result',
    'technical education board result 2025',
    'bteb 1st semester result 2025',
    'bteb result zone 2025',
    'bteb board result',
    'bteb result 2025 date',
    'result bteb 2025',
    'bteb.result',
    'bteb diploma result',
    'bteb result 2022',
    'bd technical education board result',
    'bteb result marksheet download',
    'bteb result bd',
    'technical education board result',
    'nabteb result checker',
    'bted result',
    'bte results 2025',
    'bangladesh technical education board result check',
    'bteb রেজাল্ট ২০২৫',
    'bd diploma result',
    'diploma agriculture result 2025',
    'bteb result diploma 2025',
    'bteb result.com',
    'betb result',
    'bteb institute result',
    'btet result',
    'bangladesh technical board result',
    'diploma result checking link',
    'bteb education board result',
    'individual result bteb',
    'bangladesh technical education board result',
    'bteb result date 2025',
    'bteb result 2024',
    'diploma result 2025',
    'www.bteb.gov.bd result',
    // Additional comprehensive BTEB keywords
    'bteb',
    'web based result',
    'bteb result',
    'www.educationboard.gov.bd hsc result 2022',
    'breb',
    'bteb admission',
    'btebadmissionresult',
    'cgpa calculator',
    'diploma result',
    'www.educationboard.gov.bd ssc result 2022',
    'bangladesh technical education board',
    'bangladesh technical education board dhaka',
    'bteb gov bd',
    'education board result marksheet',
    'web based result with marksheet',
    'www bteb gov bd',
    'bteb notice',
    'dhaka polytechnic',
    'dhaka polytechnic institute',
    'ssc gpa calculator',
    'hsc gpa calculator',
    'bteb admission result',
    'www bteb gov bd result',
    'hsc result 2023 published date',
    'all result bd',
    'bteb admission 2023',
    'gpa calculator hsc',
    'www.educationboard.gov.bd ssc result 2021',
    'eboard result',
    'web based result publication system for education boards',
    'www fisheries gov bd',
    'www.educationboard.gov.bd hsc result 2023',
    'www.educationboard.gov.bd ssc result 2020',
    'bteb result 2023',
    'gpa calculator bd',
    'www.educationboard.gov.bd hsc result 2021',
    'bteb gov bd result',
    'bteb result marksheet',
    'cgpa',
    'hsc result 2022 published date',
    'karigori shikkha board',
    'polytechnic result',
    'rajshahi polytechnic institute',
    'rangpur polytechnic institute',
    'ssc board challenge result 2022',
    'web based result publication',
    'www.agriculture.ac.bd admission 2020-21',
    'bangladesh karigori shikkha board',
    'bangladesh technical education board result',
    'bord challenge',
    'bteb diploma result',
    'diploma engineering result',
    'khulna polytechnic institute',
    'mymensingh polytechnic institute',
    'www bteb gov bd new notice',
    'www.bteb.gov.bd result 2023',
    'www.btebadmission.gov.bd 2022',
    'board chalange',
    'board challenge',
    'breb online application',
    'dinajpur polytechnic institute',
    'dte bd',
    'eboard result com',
    'iub cgpa calculator',
    'nursing admission 2021-22 in bangladesh',
    'polytechnic admission result 2022',
    'www.bteb.gov.bd result 2022',
    'brtc gov bd',
    'bteb notice 2021',
    'diploma result marksheet',
    'munshiganj polytechnic institute',
    'polytechnic admission result',
    'resultbd',
    'sylhet polytechnic institute',
    'www.educationboard.gov.bd hsc result 2020',
    'barisal polytechnic institute',
    'betb',
    'bteb admission 2022',
    'bteb gov bd notice',
    'bteb result marksheet 2022',
    'diploma in engineering result',
    'diploma result checking link',
    'diploma results 2018',
    'dte gov bd',
    'hsc result 2022 with marksheet',
    'individual result',
    'institute of diploma engineers bangladesh',
    'newresult bd com',
    'ssc board challange result',
    'ssc board challenge result',
    'ssc vocational result 2022',
    'www dte gov bd',
    'bangladesh institute of glass and ceramics',
    'breb result 2021',
    'btb',
    'bteb exam routine 2023',
    'bteb result hub',
    'cgpa result',
    'cgpa system in bangladesh',
    'diploma admission result 2018',
    'faridpur polytechnic institute',
    'hsc bm result 2023',
    'magura polytechnic institute',
    'ssc board challenge 2022',
    'tangail polytechnic',
    'tangail polytechnic institute',
    'www result bd com',
    'bangladesh technical education board result 2023',
    'bteb admission system',
    'bteb result check',
    'cgpa calculator for diploma',
    'chittagong polytechnic',
    'chittagong polytechnic institute',
    'ctg polytechnic institute',
    'diploma result bd',
    'eboardresult marksheet 2021',
    'feni polytechnic institute',
    'how to calculate cgpa',
    'how to count cgpa',
    'how to find cgpa',
    'hsc board challenge 2024',
    'hsc board challenge result 2023',
    'kurigram polytechnic institute',
    'kushtia govt college',
    'pabna textile',
    'ssc vocational result 2023',
    'technical education board result',
    'www brtc gov bd',
    'www bteb gov bd com',
    'www.brtc.gov.bd result 2021',
    'www.bteb.gov.bd admission 2023',
    'based result',
    'brahmanbaria polytechnic institute',
    'btb bd',
    'bte',
    'bteb admission gov bd',
    'bteb admission notice',
    'bteb result app',
    'bteb routine 2021',
    'btebadmission.gov.bd 2020-21',
    'btebadmission.gov.bd 2022',
    'bted',
    'cox\'s bazar polytechnic institute',
    'diploma result 2020',
    'hsc bm result 2022',
    'hsc bmt result 2023',
    'lakshmipur polytechnic institute',
    'laxmipur polytechnic institute',
    'naogaon polytechnic institute',
    'polytechnic result 2022',
    'ssc result calculator',
    'technical board result',
    'web based result publication system',
    'www web based result',
    'all result',
    'bangladesh institute of marine technology',
    'bangladesh polytechnic institute',
    'bhola polytechnic institute',
    'board challenge hsc 2024',
    'bteb bd',
    'cgpa calculator bd',
    'cgpa calculator brac',
    'cgpa result 2022',
    'diploma admission result',
    'diploma in engineering result 2022',
    'hope polytechnic institute',
    'how to calculate cgpa out of 4',
    'hsc board challenge result 2022',
    'hsc result published date 2023',
    'hsc vocational routine 2023 pdf download',
    'karigori board',
    'mangrove institute of science and technology',
    'moulvibazar polytechnic institute',
    'polytechnic notice',
    'shariatpur polytechnic institute',
    'shariyatpur polytechnic institute',
    'sirajganj polytechnic institute',
    'ssc rajal',
    'ssc vocational routine 2021',
    'www educationboard gov bd hsc result 2022',
    'www.bteb.gov.bd result 2021',
    'barguna polytechnic institute',
    'bd result app',
    'brtc admit card',
    'bteb exam routine 2021',
    'bteb notice ssc 2022',
    'bteb result 2022 pdf download',
    'bteb result bd',
    'bteb result com',
    'bteb result marksheet 2023',
    'cgpa point',
    'computer office application',
    'dhaka political institute',
    'dip gov bd',
    'diploma engineering result 2023',
    'eboardresult.com 2021',
    'gpa calculator for ssc',
    'grading system bangladesh',
    'graphic arts institute',
    'hsc bm 1st year result 2023',
    'hsc result 2021 published date',
    'jashore polytechnic institute',
    'national institute of engineering & technology niet dhaka',
    'satkhira polytechnic institute',
    'ssc 2022 board challenge result',
    'ssc vocational result',
    'web based result hsc',
    'www btv gov bd',
    'www eboardresult com',
    'www educationboard gov bd hsc result 2023',
    'www.eboardresult.gov.bd ssc',
    'ayub hena polytechnic institute',
    'satisfyhost',
    'www educationboard gov bd hsc result 2021'
  ],
  authors: [{ name: 'BTEB Results Hub' }],
  creator: 'BTEB Results Hub',
  publisher: 'BTEB Results Hub',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://btebresultshub.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'BTEB Results Hub',
    description: 'Check individual BTEB results and calculate CGPA online.',
    url: 'https://btebresultshub.com',
    siteName: 'BTEB Results Hub',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'BTEB Results Hub - Check Diploma & Polytechnic Results Online',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BTEB Results Hub',
    description: 'Check BTEB diploma results and calculate CGPA online.',
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'G-QGCT6S6VB1',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "BTEB Results Hub",
    "description": "Check individual BTEB results and calculate CGPA online with regulation-based weights.",
    "url": "https://btebresultshub.com",
    "applicationCategory": "EducationApplication",
    "operatingSystem": "Web Browser",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "provider": {
      "@type": "Organization",
      "name": "BTEB Results Hub",
      "url": "https://btebresultshub.com"
    },
    "featureList": [
      "BTEB Result Search",
      "Diploma Result Check",
      "Polytechnic Result Check",
      "Engineering Results",
      "Technology Results",
      "Agriculture Results",
      "GPA Calculation",
      "Semester Results",
      "Referred Subjects",
      "BTEB Roll Number Search",
      "Diploma Roll Number Search",
      "Polytechnic Roll Number Search"
    ],
    "keywords": "bteb results, diploma result, polytechnic result, bangladesh technical education board, bteb result check, diploma engineering result, polytechnic institute result, bteb 2025 result, diploma 2025 result, polytechnic 2025 result",
    "about": {
      "@type": "EducationalOrganization",
      "name": "Bangladesh Technical Education Board",
      "alternateName": "BTEB",
      "description": "Official board for technical education in Bangladesh"
    },
    "audience": {
      "@type": "EducationalAudience",
      "educationalRole": "student"
    },
    "educationalUse": "assessment",
    "learningResourceType": "assessment",
    "educationalLevel": "diploma"
  };

  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        <link rel="canonical" href="https://btebresultshub.com" />
        <meta name="theme-color" content="#2563eb" />
        <meta name="msapplication-TileColor" content="#2563eb" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
      </head>
      <body className={inter.className}>
        <GoogleAnalytics />
        <NavBar />
        {children}
      </body>
    </html>
  )
}
